// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNaiUBdYg-r1S4Lg4f1u7D3vQKYslxW4s',
    appId: '1:11124817016:web:1afc778e67ea0987a9018d',
    messagingSenderId: '11124817016',
    projectId: 'phoneauthh-204f9',
    authDomain: 'phoneauthh-204f9.firebaseapp.com',
    storageBucket: 'phoneauthh-204f9.appspot.com',
    measurementId: 'G-HHPL92MKRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJeXg1B44SXozbi1F9BORtyrearMS6UqU',
    appId: '1:11124817016:android:fbc66e24943fc1baa9018d',
    messagingSenderId: '11124817016',
    projectId: 'phoneauthh-204f9',
    storageBucket: 'phoneauthh-204f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByhHYUlziUZ-PTYMTOFJlKW7nF3kfwZP0',
    appId: '1:11124817016:ios:c580d912566a89cda9018d',
    messagingSenderId: '11124817016',
    projectId: 'phoneauthh-204f9',
    storageBucket: 'phoneauthh-204f9.appspot.com',
    iosBundleId: 'com.example.phoneauthh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByhHYUlziUZ-PTYMTOFJlKW7nF3kfwZP0',
    appId: '1:11124817016:ios:c580d912566a89cda9018d',
    messagingSenderId: '11124817016',
    projectId: 'phoneauthh-204f9',
    storageBucket: 'phoneauthh-204f9.appspot.com',
    iosBundleId: 'com.example.phoneauthh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNaiUBdYg-r1S4Lg4f1u7D3vQKYslxW4s',
    appId: '1:11124817016:web:5a313c295688de05a9018d',
    messagingSenderId: '11124817016',
    projectId: 'phoneauthh-204f9',
    authDomain: 'phoneauthh-204f9.firebaseapp.com',
    storageBucket: 'phoneauthh-204f9.appspot.com',
    measurementId: 'G-D85HM1ZMJ1',
  );
}
